<?php
// Auto-generated by build.mjs from site.config.mjs. Do not edit by hand.
return [
    'whatsapp' => '595992279599',
    'phone_display' => '+595 992 279 599',
    'site_url' => 'https://pozo.com.py',
    'crm_url' => 'https://crm.clientes.com.py',
    'generated_at' => '2026-09-28T20:10:16.902Z',
];
